"""Rules for what /add_building accepts, checked without a database."""

import pytest

from app.payload import Column, PayloadError, insert_column_order, normalize_rows

# Mirrors a realistic table: a database-generated id, then writable columns.
COLUMNS = {
    "id": Column("id", insertable=False),
    "name": Column("name", insertable=True),
    "building_type": Column("building_type", insertable=True),
    "latitude": Column("latitude", insertable=True),
    "longitude": Column("longitude", insertable=True),
    "floors": Column("floors", insertable=True),
    "label": Column("label", insertable=False),
}

VALID = {"name": "Hospital", "latitude": 41.84, "longitude": 1.30}


def check(payload, **overrides):
    kwargs = {
        "latitude_column": "latitude",
        "longitude_column": "longitude",
        "columns": COLUMNS,
        "max_rows": 1000,
    }
    kwargs.update(overrides)
    return normalize_rows(payload, **kwargs)


def test_single_object_becomes_one_row() -> None:
    assert check(VALID) == [VALID]


def test_list_is_kept_as_is() -> None:
    assert check([VALID, VALID]) == [VALID, VALID]


def test_integer_coordinates_are_accepted() -> None:
    assert check({"name": "X", "latitude": 41, "longitude": 1}) == [
        {"name": "X", "latitude": 41, "longitude": 1}
    ]


@pytest.mark.parametrize(
    ("payload", "message"),
    [
        ([], "No rows provided"),
        ({}, "is empty"),
        ({**VALID, "lattitude": 1}, "unknown column"),
        ({**VALID, "id": 7}, "generated by the database"),
        ({**VALID, "label": "x"}, "generated by the database"),
        ({"name": "X", "longitude": 1.3}, "'latitude' is required"),
        ({"name": "X", "latitude": 41.8}, "'longitude' is required"),
        ({**VALID, "latitude": None}, "must not be null"),
        ({**VALID, "latitude": "41.8"}, "must be a number"),
        ({**VALID, "latitude": True}, "must be a number"),
        ({**VALID, "latitude": 91}, "between -90 and 90"),
        ({**VALID, "longitude": -181}, "between -180 and 180"),
    ],
)
def test_rejected_payloads(payload, message: str) -> None:
    with pytest.raises(PayloadError, match=message):
        check(payload)


def test_row_index_is_reported_for_bulk_payloads() -> None:
    with pytest.raises(PayloadError, match="row 1"):
        check([VALID, {**VALID, "latitude": 91}])


def test_row_cap_is_enforced() -> None:
    with pytest.raises(PayloadError, match="at most 2 per request"):
        check([VALID, VALID, VALID], max_rows=2)


def test_coordinate_columns_must_exist_in_the_table() -> None:
    with pytest.raises(PayloadError, match="no 'lat' column"):
        check(VALID, latitude_column="lat")


def test_insert_columns_follow_table_order_and_union_the_rows() -> None:
    rows = [
        {"longitude": 1.3, "latitude": 41.8, "floors": 2},
        {"name": "X", "latitude": 41.9, "longitude": 1.4},
    ]
    # Table order, not the order the keys arrived in.
    assert insert_column_order(rows, COLUMNS) == [
        "name",
        "latitude",
        "longitude",
        "floors",
    ]
