"""Validation of POST bodies against the table's actual columns.

Pure functions: no database access, so the rules are easy to test.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class Column:
    """A column of the building table, as reported by the database."""

    name: str
    insertable: bool  # false for identity/generated columns the server fills in


class PayloadError(ValueError):
    """The request body cannot be turned into an INSERT."""


def _require_coordinate(value: Any, column: str, low: float, high: float, where: str) -> None:
    if value is None:
        raise PayloadError(f"{where}: '{column}' must not be null.")
    # bool is an int subclass, and is never a sensible coordinate.
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise PayloadError(f"{where}: '{column}' must be a number, got {type(value).__name__}.")
    if not low <= float(value) <= high:
        raise PayloadError(f"{where}: '{column}' must be between {low} and {high}, got {value}.")


def normalize_rows(
    payload: dict[str, Any] | list[dict[str, Any]],
    *,
    latitude_column: str,
    longitude_column: str,
    columns: dict[str, Column],
    max_rows: int,
) -> list[dict[str, Any]]:
    """Check the body and return it as a list of rows ready to insert.

    Accepts a single object or a list of objects. Keys must be real, writable
    columns of the table, and every row must carry valid coordinates.
    """
    rows = [payload] if isinstance(payload, dict) else list(payload)

    if not rows:
        raise PayloadError("No rows provided.")
    if len(rows) > max_rows:
        raise PayloadError(f"Too many rows: {len(rows)} sent, at most {max_rows} per request.")

    for column in (latitude_column, longitude_column):
        if column not in columns:
            raise PayloadError(
                f"The table has no '{column}' column. "
                "Set LATITUDE_COLUMN / LONGITUDE_COLUMN to match the table."
            )

    writable = {name for name, col in columns.items() if col.insertable}

    for index, row in enumerate(rows):
        where = f"row {index}" if len(rows) > 1 else "row"

        if not isinstance(row, dict):
            raise PayloadError(f"{where}: expected an object, got {type(row).__name__}.")
        if not row:
            raise PayloadError(f"{where}: is empty.")

        unknown = sorted(set(row) - set(columns))
        if unknown:
            raise PayloadError(
                f"{where}: unknown column(s) {unknown}. "
                f"The table has: {sorted(columns)}."
            )

        read_only = sorted(set(row) - writable)
        if read_only:
            raise PayloadError(
                f"{where}: column(s) {read_only} are generated by the database "
                "and cannot be supplied."
            )

        for column in (latitude_column, longitude_column):
            if column not in row:
                raise PayloadError(f"{where}: '{column}' is required.")

        _require_coordinate(row[latitude_column], latitude_column, -90, 90, where)
        _require_coordinate(row[longitude_column], longitude_column, -180, 180, where)

    return rows


def insert_column_order(rows: list[dict[str, Any]], columns: dict[str, Column]) -> list[str]:
    """Columns to write, in the table's own order, for a multi-row INSERT.

    The union across rows: a row that omits one of them gets the column's
    database default instead.
    """
    used = set().union(*(set(row) for row in rows))
    return [name for name in columns if name in used]
